# Generated by Django 2.1.2 on 2018-11-08 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20181107_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='option',
        ),
        migrations.AddField(
            model_name='vote',
            name='option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Choice'),
        ),
    ]
