# Generated by Django 2.1.2 on 2018-11-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20181108_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='polllist',
            name='question',
            field=models.TextField(null=True),
        ),
    ]
